## Use VSCODE extensao "REST Client"
## Para testar o resultado do JSON PATH, 
## acesse: http://www.jsonquerytool.com/

## Use 3x # para separar uma URL da outra

### Configurações Iniciais ###
@host_path = https://localhost:44392/Api/HistoricoAPI


####################### TESTE API ########################
########### FUNDOS #############

### Todos
GET {{host_path}}

### Detalhes de um Registro
@id={{$randomInt 1 220 }}
# @name respDetail

GET {{host_path}}/{{id}}


####### PARA TESTAR O FUNCIONAMENTO  ########
## Testar se funciona as features do REST Client (VSCode)
@idDetail = {{respDetail.response.body.$.fundoId}}
GET http://httpbin.org/get?&id={{idDetail}}

### (1) Inserir

# @name respPost
POST {{host_path}}
Content-Type: application/json

{
  "valor": 100.0,
  "fundo": {
    "fundoId": 199,
    "razaoSocial": "RB CAPITAL TFO SITUS FDO INV IMOB - FII",
    "sigla": "RBTS11"
  },
  "data": "2019-03-03T00:00:00"
}

### Testar a adicão do registro acima (1)

GET {{host_path}}/{{respPost.response.body.fundoId}}

### Remove a adição do registro anterior (1)
DELETE {{host_path}}/{{respPost.response.body.fundoId}}